import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Car Doctor",
    template: "%s | Car Doctor",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${geistMono.className} antialiased`}>
        <div>
          <Navbar></Navbar>
          <main className="max-w-[1250px] mx-auto min-h-screen">{children}</main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
